version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: hr-management-api
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      PORT: 8080
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app:cached
      - /usr/src/app/node_modules
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:8080/health || exit 1
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 5s

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD:
      MYSQL_DATABASE: hr_management_system
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d:ro
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: mysqladmin ping -h localhost || exit 1
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
